version: '3.7'

services:
    sulmun2yong-test-mysql:
        image: mysql:8.0.35
        container_name: sulmun2yong-test-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        expose:
            - "3306"
        ports:
            - "3306:3306"
        volumes:
            - sulmun2yong-test-mysql:/var/lib/mysql

    sulmun2yong-test-kafka:
        image: bitnami/kafka:latest
        container_name: sulmun2yong-test-kafka
        environment:
            - KAFKA_CFG_PROCESS_ROLES=broker,controller
            - KAFKA_CFG_NODE_ID=1
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@sulmun2yong-test-kafka:9093
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
            - ALLOW_PLAINTEXT_LISTENER=yes
        ports:
            - "9092:9092"
            - "9093:9093"

volumes:
    sulmun2yong-test-mysql:
