spring:
    datasource:
        url: jdbc:mysql://host:3306/db?serverTimezone=Asia/Seoul
        username: user
        password: password

    kafka:
        bootstrap-servers: url

slack:
    webhook:
        url: url
