spring:
    profiles.include:
        - secret
    application:
        name: sulmun2yong_alert
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        database: mysql
        show-sql: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MySQLDialect
                jdbc:
                    batch_size: 1000
                order_inserts: true
                order_updates: true
        generate-ddl: false

    kafka:
        consumer:
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            isolation-level: read_committed
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
    level:
        org.springframework.kafka: INFO

server:
    port: 8081

kafka:
    topics:
        survey-response: "survey-response"
        winning: "winning"
    consumer-groups:
        survey-response: "survey_response_notification_group"
        winning: "winning_notification_group"
